FROM nginx:alpine
LABEL Maintainer="sean bourg <sean.bourg@gmail.com>"

ARG CONTAINER_SOURCE=site

RUN apk update && apk upgrade; 

COPY config.d/nginx /etc/nginx/conf.d

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]