version: "3.7"

# Place site and cdn servers on an internal network. All access should be through the proxy.
networks:
    app-network:
        driver: bridge
        internal: false
        
    app-internal:
        driver: bridge
        internal: true

services: 
    proxy:
        container_name: "${CONTAINER_NAME_PROXY:-proxy-instance}"
        image: "${IMAGE_NAME_PROXY:-static-proxy-image}"
        build: 
            context: .
            dockerfile: Containerfile-proxy
        networks:
            - app-network
            - app-internal
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - site
            - cdn
        links: 
            - site
            - cdn
        restart: always

    cdn:
        container_name: "${CONTAINER_NAME_CDN:-cdn-instance}"
        image: "${IMAGE_NAME_CDN:-static-cdn-image}"
        build: 
            context: .
            dockerfile: Containerfile-nginx
            args:
                - BUILD_SOURCE=cdn             
        volumes:
            - ./test-site/media:/var/www/media:ro
            - ./test-site/css:/var/www/css:ro
        networks: 
            - app-internal
        ports:
            - "8080:80"
        restart: always

    site:
        container_name: "${CONTAINER_NAME_SITE:-site-instance}"
        image: "${IMAGE_NAME_SITE:-static-site-image}"
        build: 
            context: .
            dockerfile: Containerfile-nginx    
            args:
                - BUILD_SOURCE=site
        volumes:
            - ./test-site/html:/var/www:ro
        networks:
            - app-internal
        ports:
            - "8081:80"
        restart: always
